# Generated by Django 5.0.1 on 2025-11-18 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "habits_stack",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_micro_habit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="habit",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitentry",
            name="points_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "Health"),
                    ("productivity", "Productivity"),
                    ("learning", "Learning"),
                    ("fitness", "Fitness"),
                    ("mindfulness", "Mindfulness"),
                    ("social", "Social"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habitentry",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="habitentry",
            name="note",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name="habit",
            unique_together={("user", "title")},
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "-created_at"], name="habits_habi_user_id_c66d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["user", "is_active"], name="habits_habi_user_id_f5e729_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["user", "category"], name="habits_habi_user_id_35e2ba_idx"),
        ),
        migrations.AddIndex(
            model_name="habitentry",
            index=models.Index(fields=["habit", "-date"], name="habits_entr_habit_i_6cb94a_idx"),
        ),
        migrations.AddIndex(
            model_name="habitentry",
            index=models.Index(
                fields=["habit", "completed"], name="habits_entr_habit_i_645561_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="habit",
            table="habits_habit",
        ),
        migrations.AlterModelTable(
            name="habitentry",
            table="habits_entry",
        ),
        migrations.AddField(
            model_name="habitstack",
            name="anchor_habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stacked_habits",
                to="habits.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitstack",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stacks",
                to="habits.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitstack",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_stacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="habitstack",
            unique_together={("habit", "anchor_habit")},
        ),
    ]
