# Generated by Django 5.2.8 on 2025-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0004_add_bookmark_and_feed_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="feed_item",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="feeditem",
            name="habits_feeditem_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="reaction",
            name="habits_reaction_summary_idx",
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
