# Generated by Django 5.2.8 on 2025-11-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("habits", "0003_badge_challenge_feeditem_comment_habitcontract_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("water_trees", "Water Multiple Trees"),
                            ("care_variety", "Different Care Actions"),
                            ("weather_bonus", "Weather-based Challenge"),
                            ("creature_attract", "Attract Forest Creatures"),
                            ("growth_target", "Tree Growth Target"),
                            ("decoration_place", "Forest Decoration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("target_value", models.IntegerField()),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("points_reward", models.IntegerField(default=50)),
                ("special_rewards", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "forest_daily_challenge",
            },
        ),
        migrations.CreateModel(
            name="ForestAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_tree", "First Tree Planted"),
                            ("forest_level", "Forest Level Milestone"),
                            ("care_streak", "Daily Care Streak"),
                            ("weather_master", "Weather Event Master"),
                            ("decorator", "Forest Decorator"),
                            ("creature_friend", "Creature Whisperer"),
                            ("ancient_tree", "Ancient Tree Grower"),
                            ("seasonal", "Seasonal Champion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("required_level", models.IntegerField(default=1)),
                ("required_points", models.IntegerField(default=0)),
                ("required_actions", models.JSONField(blank=True, default=dict)),
                ("points_reward", models.IntegerField(default=0)),
                ("unlocks", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "forest_achievement",
            },
        ),
        migrations.CreateModel(
            name="ForestDecoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decoration_type",
                    models.CharField(
                        choices=[
                            ("rock", "Rock"),
                            ("flower", "Flower"),
                            ("stream", "Stream"),
                            ("path", "Path"),
                            ("bench", "Bench"),
                            ("fountain", "Fountain"),
                            ("bridge", "Bridge"),
                            ("mushroom", "Mushroom"),
                            ("bush", "Bush"),
                            ("statue", "Statue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decoration_id", models.CharField(max_length=50)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z_index", models.IntegerField(default=0)),
                ("scale", models.FloatField(default=1.0)),
                ("rotation", models.FloatField(default=0.0)),
                ("opacity", models.FloatField(default=1.0)),
                ("required_level", models.IntegerField(default=1)),
                ("required_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_decorations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_decoration",
            },
        ),
        migrations.CreateModel(
            name="ForestLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("forest_level", models.IntegerField(default=1)),
                ("total_points", models.IntegerField(default=0)),
                (
                    "current_season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        default="spring",
                        max_length=20,
                    ),
                ),
                (
                    "weather_state",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                        ],
                        default="sunny",
                        max_length=20,
                    ),
                ),
                ("is_night", models.BooleanField(default=False)),
                ("unlocked_tree_types", models.JSONField(blank=True, default=list)),
                ("unlocked_decorations", models.JSONField(blank=True, default=list)),
                ("unlocked_creatures", models.JSONField(blank=True, default=list)),
                ("auto_weather", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("day_night_cycle", models.BooleanField(default=True)),
                ("total_waterings", models.IntegerField(default=0)),
                ("total_prunings", models.IntegerField(default=0)),
                ("total_fertilizations", models.IntegerField(default=0)),
                ("trees_planted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_layout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_layout",
            },
        ),
        migrations.CreateModel(
            name="TreePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z_index", models.IntegerField(default=0)),
                ("size_multiplier", models.FloatField(default=1.0)),
                ("health_bonus", models.FloatField(default=0.0)),
                ("last_watered", models.DateTimeField(blank=True, null=True)),
                ("last_pruned", models.DateTimeField(blank=True, null=True)),
                ("last_fertilized", models.DateTimeField(blank=True, null=True)),
                ("tree_type", models.CharField(blank=True, max_length=50)),
                ("custom_color", models.CharField(blank=True, max_length=7)),
                (
                    "growth_stage",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("sapling", "Sapling"),
                            ("young", "Young"),
                            ("mature", "Mature"),
                            ("ancient", "Ancient"),
                        ],
                        default="sapling",
                        max_length=20,
                    ),
                ),
                ("is_diseased", models.BooleanField(default=False)),
                ("disease_cure_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_position",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_tree_position",
                "unique_together": {("user", "habit")},
            },
        ),
        migrations.CreateModel(
            name="ForestCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "creature_type",
                    models.CharField(
                        choices=[
                            ("rabbit", "Rabbit"),
                            ("bird", "Bird"),
                            ("butterfly", "Butterfly"),
                            ("squirrel", "Squirrel"),
                            ("owl", "Owl"),
                            ("deer", "Deer"),
                            ("firefly", "Firefly"),
                            ("bee", "Bee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visit_start", models.DateTimeField(auto_now_add=True)),
                ("visit_duration", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("animation_state", models.CharField(default="idle", max_length=20)),
                ("x_offset", models.FloatField(default=0.0)),
                ("y_offset", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_creatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatures",
                        to="forest.treeposition",
                    ),
                ),
            ],
            options={
                "db_table": "forest_creature",
            },
        ),
        migrations.CreateModel(
            name="WeatherEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weather_type",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                            ("drought", "Drought"),
                            ("foggy", "Foggy"),
                            ("snowy", "Snowy"),
                            ("windy", "Windy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("duration_hours", models.IntegerField(default=6)),
                ("is_active", models.BooleanField(default=True)),
                ("growth_multiplier", models.FloatField(default=1.0)),
                ("points_multiplier", models.FloatField(default=1.0)),
                ("special_effects", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_weather",
            },
        ),
        migrations.CreateModel(
            name="ForestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("water", "Water Tree"),
                            ("prune", "Prune Tree"),
                            ("fertilize", "Fertilize Tree"),
                            ("plant", "Plant Tree"),
                            ("move", "Move Tree"),
                            ("decorate", "Add Decoration"),
                            ("weather_change", "Weather Change"),
                            ("season_change", "Season Change"),
                            ("creature_visit", "Creature Visit"),
                            ("achievement", "Achievement Unlock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("weather_at_time", models.CharField(blank=True, max_length=20)),
                ("season_at_time", models.CharField(blank=True, max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forest.treeposition",
                    ),
                ),
            ],
            options={
                "db_table": "forest_action",
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="forest_acti_user_id_f3fcfd_idx"
                    ),
                    models.Index(
                        fields=["user", "action_type"], name="forest_acti_user_id_25ae7b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="forest.dailychallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_user_daily_challenge",
                "unique_together": {("user", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="UserForestAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("progress", models.JSONField(blank=True, default=dict)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="forest.forestachievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forest_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forest_user_achievement",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
