# Generated by Django 5.0.1 on 2025-11-19 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_alter_user_options_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="identity",
            field=models.CharField(
                blank=True, help_text="Identity statement e.g., 'Runner', 'Reader'", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="identity_progress",
            field=models.IntegerField(
                default=0, help_text="0-100 percent progress toward identity"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_follow",
                "unique_together": {("follower", "following")},
            },
        ),
    ]
